---
abstract: 'An ORM emphasizing prefetching'
author:
  - 'Clinton Wolfe <CLWOLFE@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-ReluctantORM
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: 0
  DBI: 0
  Data::Diff: 0
  Exception::Class: 1.3
  IO::Scalar: 0
  JSON: 0
  Lingua::EN::Inflect: 0
  NEXT: 0
  Regexp::Common: 0
  SQL::Statement: 0
  Sub::Name: 0.05
  Test::Exception: 0
  aliased: 0
version: 0.52_0
